### ISSUE TITLE
Move CI workflows that could be re-used to shared repo

### ISSUE THREAD

**Issue by Andrey9kin** [fivexl/github-reusable-workflows#1]
Move what is possible to re-use from sso elevator and create re-usable workflows for Python and Terraform

Python
- python pep8
- pylint
- python unit test

Terraform
- terraform fmt
- terraform validate
- terraform doc
- tfsec
- tflint

https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow

**Comment by EreminAnton** [comment]
It appears that the [pre-commit tf_docs](https://github.com/antonbabenko/pre-commit-terraform) and [gh-actions tf_docs](https://github.com/terraform-docs/gh-actions) are not compatible out-of-the-box.

When I generate docs using the command: `terraform-docs markdown table --indent 2 --output-mode inject --output-file README.md ./` the GitHub actions (tfdocs) pass. 
However, when the documentation is generated by the pre-commit hook, the CI fails with this [error](https://github.com/fivexl/terraform-aws-sso-elevator/actions/runs/5209054543/jobs/9398397719).
